name: certare_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  cupertino_icons: ^1.0.2
  flutter_datetime_picker: ^1.5.1
  mask_text_input_formatter: ^2.4.0
  intl: ^0.18.1
  multi_select_flutter: ^4.1.3
  pdf: ^3.10.1
  path_provider: ^2.0.15
  open_file: ^3.3.1
  printing: ^5.10.4
  image_picker: ^0.8.7+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/certare.png
   
  fonts:
    - family: Prototype
      fonts:
        - asset: assets/fonts/Prototype.ttf